### PR TITLE
dotty remove unnecessary constraints

### PR DESCRIPTION
**Pull request by jtjeferreira**

### CODE REVIEW

**Comment by dwijnand** [comment]
Initial thread: https://github.com/playframework/play-json/pull/572#discussion_r578435998

I wonder if this works because it just keeps summoning new instances instead of reusing?

**Comment by jtjeferreira** [comment]
> I wonder if this works because it just keeps summoning new instances instead of reusing?

I see your point. Any idea how I can write an unit test for that?

**Comment by dwijnand** [comment]
Hmm, perhaps just do something like this?

```scala
object Foo {
  private val counter = AtomicInteger(0)
  implicit def reads: Reads[Foo] = {
    counter.inc()
    Json.reads[Foo]
  }
}
```

**Comment by SethTisue** [comment]
@jtjeferreira interested in returning to this?

**Comment by jtjeferreira** [comment]
@SethTisue I think is better to close it. I wont have time soon :(

**Pull request closed without merging**
