### PR TITLE
sbt 1.5.0

### PR DESCRIPTION
**Pull request by sullis**
# Pull Request Checklist

* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you updated the documentation?
* [ ] Have you added tests for any changed functionality?

### CODE REVIEW

**Comment by SethTisue** [comment]
@griggt a177e3ba288dac9dc0a489b67f47cdc038c05fa6 is good enough for now, I guess

**Comment by griggt** [comment]
@SethTisue see https://github.com/sullis/play-json/compare/sbt-1.5.0...griggt:sbt-1.5.0 for a fix for the conflicting scala-xml cross version issue.

This removes the need for `for3Use2_13` on ScalaTest and ScalaCheck, which in turn permits the removal of the `ScalaTestPosition` shims.  I think it should also allow for cleaning up (and probably merging) the two version-dependent `illTyped.scala` files... I ran out of time to try that tonight, sorry.

**Comment by lightbend-cla-validator** [comment]
Hi @griggt,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by SethTisue** [comment]
@griggt I cherry-picked your commit — mind signing the Lightbend CLA?

**Comment by griggt** [comment]
CLA signed.  If there's no urgency to merge this, I can probably find time today to try cleaning up `illTyped.scala` as well.

**Comment by SethTisue** [comment]
>  I can probably find time today to try cleaning up illTyped.scala as well

I did that myself just now in 9fb27bec176692e973cae69309b5eeaa272b4f76 but it didn't work:

```
[error] -- Error: /Users/tisue/play-json/play-json/shared/src/test/scala/play/api/libs/json/JsonSharedSpec.scala:137:6 
[error] 137 |      "js.toJsObject(1)" mustNot typeCheck
[error]     |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |      The 'mustNot typeCheck' syntax only works with String literals.
```

if you want to dig into that, that'd be awesome

**Comment by SethTisue** [comment]
Tell you what, I'll pull your commit from this PR to get it mergeable, then we can worry about `illTyped` in a separate PR.

**Comment by griggt** [comment]
Sounds good. I'm actually looking through it now, but at first glance it looks like a bug in the ScalaTest macro implementation of the `shouldNot typeCheck` / `mustNot typeCheck` syntax for Scala 3.

I've patched it locally to get it to work, but I need to do a deeper dive to really understand what's going on (and hopefully be able to PR a fix).

**Review by SethTisue — APPROVED** [review]

**Comment by SethTisue** [comment]
new PR: #597

**Pull request merged**
