### PR TITLE
Preserve order of fields in JsObject

### PR DESCRIPTION
**Pull request by tototoshi**
Fixed https://github.com/playframework/play-json/issues/236

By https://github.com/playframework/play-json/commit/4a3e3b036c0d79e3c01a066cdb929f520052e7ae, JsObject#underlying are changed from scala.collection.mutable.LinkedHashMap to
scala.collection.Map that wraps java.util.LinkedHashMap.
Since new instances created With ++/+/- methods of the map are not LinkedHashMap based,
JsObject.++/+/- don't preserve the order of fields. We need to use ++=/+=/-= instead.

### CODE REVIEW

**Comment by ignasi35** [comment]
I'm a bit divided.

https://github.com/playframework/play-json/commit/4a3e3b036c0d79e3c01a066cdb929f520052e7ae added a performance hit for the sake of security and this change increases allocations and object shuffling for correctness.

I think we must merge but I wonder if we're causing a perf degradation.

**Comment by renatocaval** [comment]
@ignasi35, 4a3e3b036c0d79e3c01a066cdb929f520052e7ae moves to `java.util.LinkedHashMap` to better handle hash colision. But the intention is defeated whenever the `JsObject` is manipulated because we fallback to `mutable.LinkedHashMap`. Without this fix, 4a3e3b036c0d79e3c01a066cdb929f520052e7ae is practically useless, if I understand it correctly. 

Maybe we can try to avoid the extra allocation by keeping a `java.util.LinkedHashMap` as the underlying type.

**Comment by ignasi35** [comment]
> Without this fix, [4a3e3b0](https://github.com/playframework/play-json/commit/4a3e3b036c0d79e3c01a066cdb929f520052e7ae) is practically useless flawed, if I understand it correctly.

True, I missed that detail. But my point still holds.

**Comment by exp0nge** [comment]
Possible to merge this and backport to 2.7.x?

**Comment by marcospereira** [comment]
@exp0nge right now we don't have the bandwidth to backport it to 2.7.x. I appreciate the effort done here, but I think we should revert the changes here. According to [RFC 7159](https://tools.ietf.org/html/rfc7159#page-3), the fields in an object are unordered:

> An object is an **unordered** collection of zero or more name/value pairs, where a name is a string, and a value is a string, number, boolean, null, object, or array.

I don't see a reason to go against the RFC and ensure the order here, and this is not expressed in the API either. Why is the order relevant to you here?

**Comment by sihil** [comment]
My 2p worth on this. 

The JsObject has always had a comment on `fields` saying that the order from the constructor is preserved which indicates that this was intentional, albeit untested, behaviour. It follows that further additions should also preserve order.

Whilst the spec doesn't specify any ordering, it is, for example, helpful for humans reading API responses to have fields logically grouped together and without this fix this would not be possible. Thanks @tototoshi.

**Pull request merged**
