### PR TITLE
replace Bintray with Sonatype via sbt-ci-release

### PR DESCRIPTION
**Pull request by SethTisue**
references #600
references #578

### CODE REVIEW

**Comment by SethTisue** [comment]
I'll resume work on this in a few days

**Comment by SethTisue** [comment]
@ennru can you add the necessary secrets to the repo?

**Comment by SethTisue** [comment]
@ennru ping

**Comment by octonato** [comment]
@SethTisue, I will add the credentials

**Comment by octonato** [comment]
Secrets are added. 

I agree that nobody is ask for snapshots. Until someone asks. ;-)

On the other hand, we can always create snapshot'ish tags (2.10.0-adfwe23 or 2.10.0-beta1) when someone needs something.

**Pull request merged**
