### PR TITLE
Bumps Jackson to 2.11.4

### PR DESCRIPTION
**Pull request by ignasi35**
refs https://github.com/akka/akka/pull/30130

### CODE REVIEW

**Review by mkurz — APPROVED** [review]
LGTM

**Review by marcospereira — APPROVED** [review]
LGTM!

**Comment by mkurz** [comment]
I guess we have do the same now in Play (also for the 2.8.x branch)?
https://github.com/playframework/playframework/blob/master/project/Dependencies.scala#L33-L34

**Comment by ignasi35** [comment]
> I guess we have do the same now in Play (also for the 2.8.x branch)?
> [https://github.com/playframework/playframework/blob/master/project/Dependencies.scala#L33-L34](https://github.com/playframework/playframework/blob/master/project/Dependencies.scala?rgh-link-date=2021-03-23T21%3A55%3A36Z#L33-L34)

You read my mind: https://github.com/playframework/playframework/pull/10781

**Pull request merged**
