### PR TITLE
Configure travis to have Java 9 builds

### PR DESCRIPTION
**Pull request by marcospereira**
## Purpose

Add Java 9 to our build.

### CODE REVIEW

**Comment by marcospereira** [comment]
@gmethvin maybe we should exclude the following combinations from the [build matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix):

- oraclejdk9 + scala 2.11
- oraclejdk9 + scala 2.10

WDYT?

**Comment by cchantep** [comment]
+1

**Comment by gmethvin** [comment]
@marcospereira Yes that sounds fine, just test scala 2.11/2.10 on Java 8.

**Comment by cchantep** [comment]
See #133

**Pull request closed without merging**
