### PR TITLE
Preserve zero decimal (backport to 2.9.x)

### PR DESCRIPTION
**Pull request by trbogart**
# Pull Request Checklist

* [X] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [X] Have you [squashed your commits](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits)?
* [X] Have you added copyright headers to new files?
* [x] Have you updated the documentation?
 - Updated documentation in code
* [X] Have you added tests for any changed functionality?

## Fixes

See https://github.com/playframework/play-json/pull/831 for more information. This backports that to 2.9.x.

### CODE REVIEW

**Review by gmethvin — APPROVED** [review]

**Comment by mkurz** [comment]
@trbogart
First: You need to run `sbt headerCreateAll` to pass the "code style" checks.
Second: There are binary incompatibles, see https://github.com/playframework/play-json/actions/runs/3967093076/jobs/6798660172, not sure if we are able to backport this pull request, @gmethvin What do you think?

@trbogart You would need to add following filters to https://github.com/playframework/play-json/blob/main/build.sbt#L53-L59 if we want to get this merged.

```
[error] play-json: Failed binary compatibility check against com.typesafe.play:play-json_2.12:2.9.3! Found 22 potential problems
[error]  * method parse(java.lang.String,play.api.libs.json.JsonParserSettings)play.api.libs.json.JsResult in object play.api.libs.json.BigDecimalParser's type is different in current version, where it is (java.lang.String,play.api.libs.json.JsonConfig)play.api.libs.json.JsResult instead of (java.lang.String,play.api.libs.json.JsonParserSettings)play.api.libs.json.JsResult
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("play.api.libs.json.BigDecimalParser.parse")
[error]  * static method parse(java.lang.String,play.api.libs.json.JsonParserSettings)play.api.libs.json.JsResult in class play.api.libs.json.BigDecimalParser's type is different in current version, where it is (java.lang.String,play.api.libs.json.JsonConfig)play.api.libs.json.JsResult instead of (java.lang.String,play.api.libs.json.JsonParserSettings)play.api.libs.json.JsResult
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("play.api.libs.json.BigDecimalParser.parse")
[error]  * method parseJsValue(Array[Byte])play.api.libs.json.JsValue in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.parseJsValue")
[error]  * method parseJsValue(java.lang.String)play.api.libs.json.JsValue in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.parseJsValue")
[error]  * method parseJsValue(java.io.InputStream)play.api.libs.json.JsValue in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.parseJsValue")
[error]  * method generateFromJsValue(play.api.libs.json.JsValue,Boolean)java.lang.String in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.generateFromJsValue")
[error]  * method prettyPrint(play.api.libs.json.JsValue)java.lang.String in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.prettyPrint")
[error]  * method jsValueToBytes(play.api.libs.json.JsValue)Array[Byte] in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.jsValueToBytes")
[error]  * method jsValueToJsonNode(play.api.libs.json.JsValue)com.fasterxml.jackson.databind.JsonNode in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.jsValueToJsonNode")
[error]  * method jsonNodeToJsValue(com.fasterxml.jackson.databind.JsonNode)play.api.libs.json.JsValue in object play.api.libs.json.jackson.JacksonJson does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("play.api.libs.json.jackson.JacksonJson.jsonNodeToJsValue")
[error]  * method this(com.fasterxml.jackson.databind.type.TypeFactory,java.lang.Class,play.api.libs.json.JsonParserSettings)Unit in class play.api.libs.json.jackson.JsValueDeserializer's type is different in current version, where it is (com.fasterxml.jackson.databind.type.TypeFactory,java.lang.Class,play.api.libs.json.JsonConfig)Unit instead of (com.fasterxml.jackson.databind.type.TypeFactory,java.lang.Class,play.api.libs.json.JsonParserSettings)Unit
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("play.api.libs.json.jackson.JsValueDeserializer.this")
[error]  * method this(play.api.libs.json.JsonParserSettings)Unit in class play.api.libs.json.jackson.JsValueSerializer's type is different in current version, where it is (play.api.libs.json.JsonConfig)Unit instead of (play.api.libs.json.JsonParserSettings)Unit
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("play.api.libs.json.jackson.JsValueSerializer.this")
[error]  * method this(play.api.libs.json.JsonParserSettings)Unit in class play.api.libs.json.jackson.PlayDeserializers's type is different in current version, where it is (play.api.libs.json.JsonConfig)Unit instead of (play.api.libs.json.JsonParserSettings)Unit
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("play.api.libs.json.jackson.PlayDeserializers.this")
[error]  * static method jsonNodeToJsValue(com.fasterxml.jackson.databind.JsonNode)play.api.libs.json.JsValue in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.jsonNodeToJsValue")
[error]  * static method jsValueToJsonNode(play.api.libs.json.JsValue)com.fasterxml.jackson.databind.JsonNode in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.jsValueToJsonNode")
[error]  * static method jsValueToBytes(play.api.libs.json.JsValue)Array[Byte] in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.jsValueToBytes")
[error]  * static method prettyPrint(play.api.libs.json.JsValue)java.lang.String in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.prettyPrint")
[error]  * static method generateFromJsValue(play.api.libs.json.JsValue,Boolean)java.lang.String in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.generateFromJsValue")
[error]  * static method parseJsValue(java.io.InputStream)play.api.libs.json.JsValue in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.parseJsValue")
[error]  * static method parseJsValue(java.lang.String)play.api.libs.json.JsValue in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.parseJsValue")
[error]  * static method parseJsValue(Array[Byte])play.api.libs.json.JsValue in class play.api.libs.json.jackson.JacksonJson is non-static in current version
[error]    filter with: ProblemFilters.exclude[StaticVirtualMemberProblem]("play.api.libs.json.jackson.JacksonJson.parseJsValue")
[error]  * method this(play.api.libs.json.JsonParserSettings)Unit in class play.api.libs.json.jackson.PlaySerializers's type is different in current version, where it is (play.api.libs.json.JsonConfig)Unit instead of (play.api.libs.json.JsonParserSettings)Unit
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("play.api.libs.json.jackson.PlaySerializers.this")
```

**Comment by gmethvin** [comment]
@mkurz The changed methods are all package-private, not part of the public API, so they should be ok to change. We just need to add the filters.

**Comment by mkurz** [comment]
@gmethvin OK cool, I didn't check the diff actually :wink:

**Comment by gmethvin** [comment]
Yeah, there were actually a lot of useful changes here to make it easier to evolve these APIs in a binary-compatible way in the future as well.

**Pull request merged**
