### PR TITLE
Codec for Locale

### PR DESCRIPTION
**Pull request by cchantep**
See playframework/playframework#7011

### CODE REVIEW

**Comment by gmethvin** [comment]
@cchantep Maybe we should abandon playframework/playframework#7011 in favor of doing it for Locale here, and write the `Lang` formats in Play in terms of `Locale`.

**Comment by cchantep** [comment]
That would require to wait a release. The other one could be refactored after json release.

**Comment by gmethvin** [comment]
I'm ok with doing another milestone after this is merged, and updating the other PR.

**Comment by cchantep** [comment]
thx

**Pull request merged**
