### PR TITLE
Scala 2.13.8

### PR DESCRIPTION
**Pull request by mkurz**
Let's see if Travis still kicks in...

### CODE REVIEW

**Comment by ihostage** [comment]
Someone should remove a Travis CI check for this repo 😄

**Comment by mkurz** [comment]
> Someone should remove a Travis CI check for this repo smile

Yes I am working on that. I was not sure what to disable. I thought maybe removing the `.travis.yml` is enough. Also I disabled 
<kbd>
</kbd>
in https://app.travis-ci.com/github/playframework/play-json/settings
Plus I removed a webhook configured in this GitHub repo.

However it seems I have to disable the Travis integration for this repositoy, which means I have to select all repositories except `play-json`, which is a bit painful:
<kbd>

</kbd>

**Comment by ihostage** [comment]
> However it seems I have to disable the Travis integration for this repositoy, which means I have to select all repositories except play-json, which is a bit painful:

Yes. And as I progress by migration from Travis to GA, you will need to remove other repositories one by one. 😄

**Comment by mkurz** [comment]
OK, Travis removed. Finally I found the correct way, using branch protection rules for this repos:
<kbd></kbd>
There you modify the checks which are required...

**Comment by mkurz** [comment]
Blocked by https://github.com/ghik/silencer/pull/71

**Comment by mkurz** [comment]
https://repo1.maven.org/maven2/com/github/ghik/silencer-plugin_2.13.8/
Let's try again.

**Comment by mkurz** [comment]
@ihostage If you approve it should get merged automatically (I can not approve my own PRs)

**Review by ihostage — APPROVED** [review]

**Comment by ihostage** [comment]
@mkurz done 😉

**Comment by mkurz** [comment]
Actually here the GitHub "merge automatically" feature was faster than mergify. Interestingly it says "mkurz merged..." but I didn't merge manually.

**Pull request merged**
